[package]
name = "boros"
description = "Tx omnivore"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/txpipe/boros"
homepage = "https://github.com/txpipe/boros"
documentation = "https://docs.rs/boros"
license = "Apache-2.0"
readme = "README.md"
authors = ["Santiago Carmuega <santiago@carmuega.me>"]


[dependencies]
pallas = "0.6.0"
# pallas = { path = "../pallas/pallas" }
hex = "0.4.3"
net2 = "0.2.37"
bech32 = "0.8.1"
clap = "3.1.3"
log = "0.4.14"
env_logger = "0.9.0"
crossterm = "0.23"
merge = "0.1.0"
config = { version = "0.12.0", default-features = false, features = ["toml"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
minicbor = "0.14.1"
prometheus_exporter = { version = "0.8.4", default-features = false }
gasket = { path = "../../gasketlibs/gasket-rs" }

# feature: kafka
kafka = { version = "0.8.0", optional = true }

# required for CI to complete successfully
openssl = { version = "0.10", optional = true, features = ["vendored"] }
thiserror = "1.0.30"

[features]
default = []
kafkasource = ["kafka", "openssl"]
